### ISSUE TITLE
p-selectbutton breaks into two line when .p-fluid applied on the parent container 

### ISSUE THREAD

**Issue by qwadrox** [primefaces/primeng-sass-theme#146]
In the past there was a rule like this in _button.scss: 
```scss
.p-fluid {
    .p-buttonset {
        display: flex;
        
        .p-button {
            flex: 1;
        }
    }
}
```
without this the button is going to be in two line when p-fluid is on:
https://primeng.org/selectbutton 
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/be41eab3-c2ce-4af8-a672-1b8d33b1a2b3">

Just added this in the browser on the docs's site: 
class="card flex justify-content-center p-fluid"
